import Menu from "@/components/layout/page";
import "@/styles/globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Demo Next App by Hung",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto flex min-h-0 max-w-6xl flex-col justify-center lg:min-h-screen lg:flex-row">
          <div className="top-0 z-10 w-full flex-col gap-4 overflow-y-auto pt-6 lg:sticky lg:flex lg:h-screen lg:w-[310px]">
            <Menu />
          </div>
          <div className="relative min-h-0 min-w-0 pt-6 lg:flex lg:flex-1 lg:justify-center">
            <div className="overflow-auto overflow-x-hidden">
              <Providers>{children}</Providers>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
